FROM golang:1.5

ENV USER root

# Install pkcs11 deps
RUN apt-get update && apt-get install -y \
	libltdl-dev \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/cloudflare/cfssl
COPY . .

# restore all deps and build
RUN go get github.com/tools/godep && godep restore && \
	go get github.com/mitchellh/gox

ENTRYPOINT ["gox"]
